# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rossini/cpp/gameengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rossini/cpp/gameengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rossini/cpp/gameengine/CMakeFiles /home/rossini/cpp/gameengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rossini/cpp/gameengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Engine2D

# Build rule for target.
Engine2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Engine2D
.PHONY : Engine2D

# fast build rule for target.
Engine2D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/build
.PHONY : Engine2D/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

src/engine/core/GameObject.o: src/engine/core/GameObject.cpp.o
.PHONY : src/engine/core/GameObject.o

# target to build an object file
src/engine/core/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/GameObject.cpp.o
.PHONY : src/engine/core/GameObject.cpp.o

src/engine/core/GameObject.i: src/engine/core/GameObject.cpp.i
.PHONY : src/engine/core/GameObject.i

# target to preprocess a source file
src/engine/core/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/GameObject.cpp.i
.PHONY : src/engine/core/GameObject.cpp.i

src/engine/core/GameObject.s: src/engine/core/GameObject.cpp.s
.PHONY : src/engine/core/GameObject.s

# target to generate assembly for a file
src/engine/core/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/GameObject.cpp.s
.PHONY : src/engine/core/GameObject.cpp.s

src/engine/core/Render.o: src/engine/core/Render.cpp.o
.PHONY : src/engine/core/Render.o

# target to build an object file
src/engine/core/Render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Render.cpp.o
.PHONY : src/engine/core/Render.cpp.o

src/engine/core/Render.i: src/engine/core/Render.cpp.i
.PHONY : src/engine/core/Render.i

# target to preprocess a source file
src/engine/core/Render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Render.cpp.i
.PHONY : src/engine/core/Render.cpp.i

src/engine/core/Render.s: src/engine/core/Render.cpp.s
.PHONY : src/engine/core/Render.s

# target to generate assembly for a file
src/engine/core/Render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Render.cpp.s
.PHONY : src/engine/core/Render.cpp.s

src/engine/core/Shader.o: src/engine/core/Shader.cpp.o
.PHONY : src/engine/core/Shader.o

# target to build an object file
src/engine/core/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Shader.cpp.o
.PHONY : src/engine/core/Shader.cpp.o

src/engine/core/Shader.i: src/engine/core/Shader.cpp.i
.PHONY : src/engine/core/Shader.i

# target to preprocess a source file
src/engine/core/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Shader.cpp.i
.PHONY : src/engine/core/Shader.cpp.i

src/engine/core/Shader.s: src/engine/core/Shader.cpp.s
.PHONY : src/engine/core/Shader.s

# target to generate assembly for a file
src/engine/core/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Shader.cpp.s
.PHONY : src/engine/core/Shader.cpp.s

src/engine/core/Window.o: src/engine/core/Window.cpp.o
.PHONY : src/engine/core/Window.o

# target to build an object file
src/engine/core/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Window.cpp.o
.PHONY : src/engine/core/Window.cpp.o

src/engine/core/Window.i: src/engine/core/Window.cpp.i
.PHONY : src/engine/core/Window.i

# target to preprocess a source file
src/engine/core/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Window.cpp.i
.PHONY : src/engine/core/Window.cpp.i

src/engine/core/Window.s: src/engine/core/Window.cpp.s
.PHONY : src/engine/core/Window.s

# target to generate assembly for a file
src/engine/core/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine2D.dir/build.make CMakeFiles/Engine2D.dir/src/engine/core/Window.cpp.s
.PHONY : src/engine/core/Window.cpp.s

third_party/glad/src/glad.o: third_party/glad/src/glad.c.o
.PHONY : third_party/glad/src/glad.o

# target to build an object file
third_party/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/third_party/glad/src/glad.c.o
.PHONY : third_party/glad/src/glad.c.o

third_party/glad/src/glad.i: third_party/glad/src/glad.c.i
.PHONY : third_party/glad/src/glad.i

# target to preprocess a source file
third_party/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/third_party/glad/src/glad.c.i
.PHONY : third_party/glad/src/glad.c.i

third_party/glad/src/glad.s: third_party/glad/src/glad.c.s
.PHONY : third_party/glad/src/glad.s

# target to generate assembly for a file
third_party/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/third_party/glad/src/glad.c.s
.PHONY : third_party/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Engine2D"
	@echo "... glad"
	@echo "... src/engine/core/GameObject.o"
	@echo "... src/engine/core/GameObject.i"
	@echo "... src/engine/core/GameObject.s"
	@echo "... src/engine/core/Render.o"
	@echo "... src/engine/core/Render.i"
	@echo "... src/engine/core/Render.s"
	@echo "... src/engine/core/Shader.o"
	@echo "... src/engine/core/Shader.i"
	@echo "... src/engine/core/Shader.s"
	@echo "... src/engine/core/Window.o"
	@echo "... src/engine/core/Window.i"
	@echo "... src/engine/core/Window.s"
	@echo "... third_party/glad/src/glad.o"
	@echo "... third_party/glad/src/glad.i"
	@echo "... third_party/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

